### ISSUE TITLE
Create rule to send email for accepted and declined sessions

### ISSUE THREAD

**Issue by rootwork** [DevSignerCon/DevSignerCon-2015#117]
Let me know if this is a possibility. I'd like to start accepting sessions (we decided to do it in "rolling" fashion this year, not all at once).

If you set up the rule I will give you the text. I will take whatever mechanism is easiest for you -- rule on taxonomy change, button that only I see on sessions that I click, VBO action -- whatever.

But if you think you won't get to this, then I want to start sending out manual emails now.

**Comment by rootwork** [comment]
Oh and I guess this is mostly addressed to @Greg-Boggs, but if @jmallison or @danlinn want to help that would be great too.

**Comment by Greg-Boggs** [comment]
I will work on this today.

**Comment by rootwork** [comment]
Any update on this? :)

**Comment by rootwork** [comment]
BTW I changed the "Denied" option label to "Declined" but I left the value as is (denied) in case you were working on this.
