### ISSUE TITLE
Change email address on session submission notifications

### ISSUE THREAD

**Issue by rootwork** [DevSignerCon/DevSignerCon-2015#84]
Set speakers@devsignercon.com as the:
- [x] To: field for session-submitted notifications
- [ ] From: field for thanks-for-your-submission emails

**Comment by rootwork** [comment]
I've changed the notification email.

Greg, you'll need to change the "from" email for the emails to submitters _just for this submission form_ to speakers@devsignercon.com.

**Comment by Greg-Boggs** [comment]
To get SPF records to work, and get our email through spam, I had to set up a white label subdomain in sendgrid. So, the email comes from mail.devsignercon.com.... I will see if I can get sendgrid to white label a root domain. The form was requiring a subdomain.

**Comment by rootwork** [comment]
I wouldn't really mind if it was coming from speakers@mail.devsignercon.com as long as when people send a message to that address it redirects to speakers@devsignercon.com. The important point is for it to come from the speakers account and not the main info account.
