### ISSUE TITLE
Updates to session submission form

### ISSUE THREAD

**Issue by rootwork** [DevSignerCon/DevSignerCon-2015#85]
- [x] Ensure that the fields "Session Status" "Room" and "Time slots" are visible on the edit form only to privileged users.
- [x] **Session title:** We probably need to ask Lisa this question, but I remember last year there were titles that were too long for the printed program. Would it be possible to set a maxlength on this field and add helptext to that effect? (I know the title field is a special snowflake of a field, so this might mean creating a custom title field and using auto_entitylabel.)
- [x] **Session slides + slides link:** If it's possible, can we put these in a fieldset and add the following helptext?

> **Optional.** You need not include slides with your submission. If your session is selected, you may upload or link to your slides before or after the conference, and you may replace them at any time. If you don't wish to share your full slide deck, you can include a set of resources instead. Following the conference, we'll be specially featuring slides from speakers who have shared them!
- [x] **Session format:** Could you a) change "Single Presentation" to just "Presentation" b) move "Roundtable discussion" into the second position, c) move this field to the first position (above the title, if possible), and d) then please replace the helptext with the following:

> **Presentation:** 45 minutes in length, for one or more speakers. Please plan at least 10 minutes at the end for questions, although you can also integrate discussion into your presentation.
> 
> **Roundtable discussion:** 45 minutes in length, an open-ended conversation with everyone in the room and you as the facilitator. You don't necessarily need to be extremely knowledgeable about the topic, but you should come with conversation starters and help shape the discussion. Be sure to think about a way to capture ideas and resources from the session!
> 
> **Hands-on workshop:** Two 45-minute sessions with a break between them (so 90 minutes total). These should be interactive, with as much "doing" as "talking." If your workshop is selected, be sure to include in your description _at least one week prior to the conference_ what people should bring or do in advance of your workshop.
- [x] **Session description:** Please add the following helptext:

> You will be able to update your session description up until the conference. But to aid our session selection process, please give as full of a picture now of what your session will look like.
- [x] **Experience level:** Can you change this to a single-line text field? What I want to do is solicit the speakers' ideas about the experience level (they can put whatever they want) and then I will make the final call in how to sort the sessions. So ultimately there will be some kind of beginner/intermediate/advanced/any option field, but speakers won't be able to access it, just me. Make sense?
- [x] **Session takeaways:** Can you remove the whole "text formats" helptext? It's appearing above the actual help text ("What will attendees walk away with?")
- [x] **Speakers:** Can you remind me how people do this, and in particular how they list multiple speakers? Do they have to create user accounts for them first? If so we need to insert some helptext to that effect. And this needs to be updated somehow: "This is the info that you entered when you first submitted the session. This info will not show on the session. Please edit the Public Profile on your user account to update the Speaker info shown on the session." (Also note it's overlapping the word "Speaker(s)")
- [x] At the top of the form, please include the following text as submission guidelines:

> **Code of conduct:** Note that all sessions must abide by the Devsigner Code of Conduct [link to it] in both the session description and session content. Submission of a session signifies that you have read and agree to abide by the Code of Conduct.
> 
> **Number of sessions:** You may submit more than one session. Please create a separate submission for each session.
> 
> **Speaker benefits:** All speakers receive a complimentary ticket to the conference. In recognition of our speakers' time, we are hoping to also provide a stipend of $50–100 to each speaker — but we have not yet been able to secure a sponsor in order to do so. We will update you ahead of the conference about whether we will be able to provide stipends.

**Comment by rootwork** [comment]
Feel free to break these out into separate issues if that would be easier. Or ask me to do that.

**Comment by Greg-Boggs** [comment]
Please add the maximum length allowed in printed titles here when we have it.

**Comment by Greg-Boggs** [comment]
Session Takeaways filter on the session format format needs a display none on the front end.

**Comment by Greg-Boggs** [comment]
Ok, the speaker bits have been cleaned up. I have required the speaker to be set, but I have not forced people to always have filled in profile fields because the validation on that requires walking the reference.
