### ISSUE TITLE
Improve login destination

### ISSUE THREAD

**Issue by rootwork** [DevSignerCon/DevSignerCon-2015#87]
When people log in, it takes them to their profile, which for now just says:

> Your Session Evaluations
> Sorry, no evaluations have been submitted yet for your session(s).

Can we either set it up to redirect people to the home page (for now) or think together about other things we could put on the profile that would be useful to people ahead of the conference?

**Comment by Greg-Boggs** [comment]
I added login destination, but no matter where I directed users to, it was confusing. So, I've disabled it, but left it there if you want to use it. Instead, I've added "No results text" with a call to action to submit a session! Wording help on the CTA welcome, just edit the view and change it!

**Comment by danlinn** [comment]
Done?

**Comment by rootwork** [comment]
Gonz did a nice job addressing the underlying issue (guiding speakers through the registration process) so this is now done.
