### ISSUE TITLE
Install better_formats or give me a way to turn off format tips

### ISSUE THREAD

**Issue by rootwork** [DevSignerCon/DevSignerCon-2015#88]
In #85 I need a way to remove the format tips display.

https://www.drupal.org/project/better_formats is one way to do this. You could install that and I'll take care of it, or you could give me some other way to remove the format tips.

Thx!

**Comment by Greg-Boggs** [comment]
Here is the sass we used to hide it last year:

#edit-field-takeaways-und-0-format {
  display: none;
}

**Comment by danlinn** [comment]
This appears to be done?

**Comment by danlinn** [comment]
Found it, added to the CSS.

Thanks,
Dan

**Comment by rootwork** [comment]
I dunno, this still wasn't fixed after the changes were merged. I decided to just make the session takeaways field plain text. It's not my preference, but the format tips made things too confusing and pushed down the field help text.
