### ISSUE TITLE
Please change the body font

### ISSUE THREAD

**Issue by rootwork** [DevSignerCon/DevSignerCon-2015#89]
It's really hard to read. Please pick something else.

Relatedly, the bold is not bold enough to stand out, and links are for some reason the same color and not underlined, so they barely stand out.

![screen shot 2016-06-24 at 4 56 49 pm](https://cloud.githubusercontent.com/assets/79733/16353264/ca0d447c-3a2c-11e6-9ae4-02123c133a54.png)

**Comment by danlinn** [comment]
Someone want to pick something and I'll make the change?

**Comment by rootwork** [comment]
https://www.google.com/fonts/specimen/Roboto for the font, Light + Black Weights

_Ideally_ the title font would stay the same, and that would just be the body font. But if that's too complicated, please just change all the fonts to Roboto.

Links should be underlined, and non-underlined on hover. Links should also be set to full-boldness (whatever strong tags have -- it's bolder than links are now).

Finally, links should be #92278F

Font and color via Gonz. Pleading for readable links from me.

**Comment by rootwork** [comment]
Also please make label elements bold or a different color or both. For instance on the user registration page http://www.devsignercon.com/member/register that would help a lot.
