### ISSUE TITLE
Give submenu items some way of appearing (dropdown etc)

### ISSUE THREAD

**Issue by rootwork** [DevSignerCon/DevSignerCon-2015#90]
http://www.devsignercon.com/conference/code-conduct is in the menu, under "Conference" but it doesn't appear when you hover over Conference...

**Comment by Greg-Boggs** [comment]
I have enabled the code of conduct link in http://www.devsignercon.com/admin/structure/menu/manage/main-menu and cleared the cache. Drop down enabled.
