### ISSUE TITLE
Theming Clean up

### ISSUE THREAD

**Issue by Greg-Boggs** [DevSignerCon/DevSignerCon-2015#93]
- [x]  Hide "text filter" Help stuff on all the forms. Especially the session submission form. and speaker bio on user form
- [x] Display none on the timezone field on the user profile form. Users don't need to set this.
- [x] Can you line up the red dot better on "speakers" field on session submissions? if this is hard, skip it.
- [x] http://www.devsignercon.com/sponsors/apply, the labels need just a tad more space so the red dot fits next to Organization / Company *, this is minor, but it's the first thing you see on the form, and it's an important form for bringing in money.
- [ ] I mucked up the design of breadcrumbs a bit, Can you fix the Sass to apply correctly again? To remove the text seperator I added edit here: www.devsignercon.com/admin/config/user-interface/easy-breadcrumb, then the css seperator and spacing should be just changing the selector target.

**Comment by danlinn** [comment]
The fourth bullet is tough as it only happens at certain page widths and without changing the structure of how these are applied (So fun in Drupal) it's not easily done.

**Comment by Greg-Boggs** [comment]
no worries then, it's not super important

**Comment by rootwork** [comment]
I don't fully understand what was being requested with the breadcrumbs, but I gave them a little more breathing room from the header, and I think they look OK. Can this be closed?

**Comment by rootwork** [comment]
Oh, one weird thing that maybe Greg knows the answer to since I think it's about Easy Breadcrumb:

The session submission page has a title (in the breadcrumbs) of "Access denied," even when you're logged in. Any ideas?

https://www.devsignercon.com/conference/session-submission

If it's not easy to fix, I'll probably just hide the breadcrumb on that form.

**Comment by Greg-Boggs** [comment]
The page for me has the crumb:

Home » What is Devsigner » Submit A Session

**Comment by Greg-Boggs** [comment]
We should be linking the home page to /members/register so they never see the access denied page unless they book mark it or something.

**Comment by rootwork** [comment]
How bizarre! Here's what I see when I'm logged in:

![screen shot 2016-07-03 at 2 35 15 pm](https://cloud.githubusercontent.com/assets/79733/16547720/7445574a-412b-11e6-84bb-a7b235b59c41.png)

**Comment by danlinn** [comment]
Greg and I chatted and we're just going to hide the breadcrumb for that page. EASY BUTTON

**Comment by danlinn** [comment]
Will remove with css

**Comment by Greg-Boggs** [comment]
.page-eform-submit-session .block-easy-breadcrumb {
  display:  none;
}
