### ISSUE TITLE
Redirect users to /member after setting password following one-time-login link

### ISSUE THREAD

**Issue by rootwork** [DevSignerCon/DevSignerCon-2015#97]
Here's the issue: I just tried the workflow of registering, and it all works except that when you login with the one-time-login link and set your password, when you save the password, it leaves you on the /member/%/edit page instead of taking you to /member/% (where the CTA to submit a session is)

Steps to reproduce:
1. Create a new account
2. Follow the one-time-login link in the confirmation email
3. Set your new password, scroll to the bottom and save

Expected behavior: Saves new password and takes you to /member/%

Actual behavior: Saves new password and keeps you on /member/%/edit

**Comment by rootwork** [comment]
And I don't know if this is expected core/LoginToboggan behavior or not. Either something we did introduced this bug, or everyone else finds this workflow fine (which seems weird to me).

**Comment by rootwork** [comment]
Oh, right, this is the behavior that PRLP fixes. Any chance we could add that module? I can configure it.

https://www.drupal.org/project/prlp

**Comment by jmallison** [comment]
Go ahead and add it via a PR.
